from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QFileDialog
from operations import Operations

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 90, 271, 111))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_x1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_x1.setObjectName("txt_x1")
        self.verticalLayout.addWidget(self.txt_x1)
        self.txt_x2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_x2.setObjectName("txt_x2")
        self.verticalLayout.addWidget(self.txt_x2)
        self.txt_x3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_x3.setObjectName("txt_x3")
        self.verticalLayout.addWidget(self.txt_x3)
        self.txt_x4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_x4.setObjectName("txt_x4")
        self.verticalLayout.addWidget(self.txt_x4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_y1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_y1.setObjectName("txt_y1")
        self.verticalLayout_2.addWidget(self.txt_y1)
        self.txt_y2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_y2.setObjectName("txt_y2")
        self.verticalLayout_2.addWidget(self.txt_y2)
        self.txt_y3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_y3.setObjectName("txt_y3")
        self.verticalLayout_2.addWidget(self.txt_y3)
        self.txt_y4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txt_y4.setObjectName("txt_y4")
        self.verticalLayout_2.addWidget(self.txt_y4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(90, 210, 271, 111))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txt_X1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_X1.setObjectName("txt_X1")
        self.verticalLayout_5.addWidget(self.txt_X1)
        self.txt_X2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_X2.setObjectName("txt_X2")
        self.verticalLayout_5.addWidget(self.txt_X2)
        self.txt_X3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_X3.setObjectName("txt_X3")
        self.verticalLayout_5.addWidget(self.txt_X3)
        self.txt_X4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_X4.setObjectName("txt_X4")
        self.verticalLayout_5.addWidget(self.txt_X4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.txt_Y1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_Y1.setObjectName("txt_Y1")
        self.verticalLayout_6.addWidget(self.txt_Y1)
        self.txt_Y2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_Y2.setObjectName("txt_Y2")
        self.verticalLayout_6.addWidget(self.txt_Y2)
        self.txt_Y3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_Y3.setObjectName("txt_Y3")
        self.verticalLayout_6.addWidget(self.txt_Y3)
        self.txt_Y4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txt_Y4.setObjectName("txt_Y4")
        self.verticalLayout_6.addWidget(self.txt_Y4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.BtnHesapla = QtWidgets.QPushButton(self.centralwidget)
        self.BtnHesapla.setGeometry(QtCore.QRect(190, 360, 75, 23))
        self.BtnHesapla.setObjectName("BtnHesapla")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 400, 81, 16))
        self.label_9.setObjectName("label_9")
        self.input_image = QtWidgets.QLabel(self.centralwidget)
        self.input_image.setGeometry(QtCore.QRect(120, 440, 61, 16))
        self.input_image.setText("")
        self.input_image.setObjectName("input_image")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(460, 90, 81, 16))
        self.label_10.setObjectName("label_10")
        self.output_image = QtWidgets.QLabel(self.centralwidget)
        self.output_image.setGeometry(QtCore.QRect(470, 120, 47, 13))
        self.output_image.setText("")
        self.output_image.setObjectName("output_image")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 20, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.BtnAddImage = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAddImage.setGeometry(QtCore.QRect(190, 330, 75, 23))
        self.BtnAddImage.setObjectName("BtnAddImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.BtnAddImage.clicked.connect(self.uploadFileButton)
        self.BtnHesapla.clicked.connect(self.confirmFilterButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "x1,y1"))
        self.label_2.setText(_translate("MainWindow", "x2,y2"))
        self.label_3.setText(_translate("MainWindow", "x3,y3"))
        self.label_4.setText(_translate("MainWindow", "x4,y4"))
        self.label_5.setText(_translate("MainWindow", "X1,Y1"))
        self.label_6.setText(_translate("MainWindow", "X2,Y2"))
        self.label_7.setText(_translate("MainWindow", "X3,Y3"))
        self.label_8.setText(_translate("MainWindow", "X4,Y4"))
        self.BtnHesapla.setText(_translate("MainWindow", "Hesapla"))
        self.label_9.setText(_translate("MainWindow", "Giriş Görüntüsü"))
        self.label_10.setText(_translate("MainWindow", "Çıkış Görüntüsü"))
        self.label_11.setText(_translate("MainWindow", "Perspektif Düzeltme"))
        self.BtnAddImage.setText(_translate("MainWindow", "Görüntü Seç"))

    _fname = ""
    def uploadFileButton(self):
        try:
            fname = QFileDialog.getOpenFileName(None, 'Open file', 
            'c:\\',"Image files (*.jpg *.gif *.png)")
            global _fname
            _fname = fname
            if fname:
                _fname = fname[0]
                self.show_image(str(fname[0]),self.input_image)
        except Exception as error:
            self.output_image.setText("Hata!!! => " + str(error))

    def show_image(self,file_path,label):
        pixmap = QtGui.QPixmap(file_path)
    
        pixmap = pixmap.scaled(QtCore.QSize(400, 406),QtCore.Qt.AspectRatioMode.KeepAspectRatio)

        label.setPixmap(pixmap)
        
        label.setScaledContents(True)
        label.setFixedSize(QtCore.QSize(400, 406))

    def confirmFilterButton(self):
        try:
            self.output_image.setText('')
            converted_image = Operations.perspektifDuzeltme(self=self,file_name=_fname)
            converted_image_path = 'converted_image.jpg'
            converted_image.save(converted_image_path)
            self.show_image(converted_image_path,self.output_image)
        except Exception as error:
            self.output_image.setText("Hata!!! => " + str(error))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setFixedSize(1200,900)
    MainWindow.show()
    sys.exit(app.exec_())
